### ISSUE TITLE
My robot can pass through obstacles

### ISSUE THREAD

**Issue by Prosat** [hjweide/pyastar2d#24]
Hello, when I use pystar2d on complex maps, the obtained path can go across obstacles. All test code provided in the project is passed. 

In the figure below, s is the start position, e is the end position, # represents the obstacle, and x represents the result path. The red line represents the position where robot go across obstalces.

Thank you very much for answering my question.

![Snipaste_2021-08-23_18-41-51](https://user-images.githubusercontent.com/23147858/130435261-77db1379-2b0a-4699-84bc-5a86d3839be3.png)

**Comment by Prosat** [comment]
Here are some params:
obstacle weights = np.inf
walkable weights = 1.0f
allow_diagonal = False

When I use python package 'pathfinding', i got correct result as follows:
![2](https://user-images.githubusercontent.com/23147858/130436318-4cbf20e5-dca0-48f6-a62c-07968a956fce.png)

**Comment by hjweide** [comment]
Could you share a link to the code and the raw map data please?

**Comment by Prosat** [comment]
OK, it's a problem of row-major order and column-major order, when I add transpose() in my ndarray every thing solved. Thank you for your reply!

**Comment by hjweide** [comment]
Great that you figured it out!

**Comment by juzt3** [comment]
i'm sorry for reviving this topic but i have the very same problem and i cannot find any way to solve it. I've tried the transpose() solution but that's not the problem with my grid.

This is my code wich converts an image in rgb to a usable np array
`    def getClusterWalkableGridV2(self, clusterID, wallValue=np.inf, minValue=1):
        filename = self.getClusterFileName(clusterID).strip('.cluster.xml')+'.png'
        filePath = f'./mappedImages/{filename}'
        maze = imageio.imread_v2(filePath)

        if maze is None:
            print(f"No file found: {filename}")
            return

        grid = maze.astype(np.float32)
        grid[grid == 0] = wallValue
        grid[grid != 0] = minValue
        grid = grid[:, :, 0]

        return grid`

**Comment by hjweide** [comment]
Could you please post the code showing how you’re calling the library and plotting the path? Note that the path is returned as matrix coordinates (i, j), not (x, y).

**Comment by hjweide** [comment]
> isn't (i, j) the same as (x, y)? cuz this letters are just names

No, `(i, j)` refers to matrix coordinates whereas `(x, y)` refers to image coordinates. If your grid looks like this:
```
1 2 3
4 5 6
7 8 9
```
then `(i, j) = (2, 1)` refers to `8` whereas `(x, y) = (2, 1)` refers to `6` (assuming the origin is top-left).

This library uses the former both to specify the start and endpoints and to return the path.

**Comment by hjweide** [comment]
Could you please post the code showing how you’re calling the library and
plotting the path? Note that the path is returned as matrix coordinates (i,
j), not (x, y).
