### ISSUE TITLE
Binaries for windows

### ISSUE THREAD

**Issue by peterchenadded** [hjweide/pyastar2d#28]
This is great, from what I could see.

Appreciate if we can get windows wheels uploaded into pypi.org

**Comment by hjweide** [comment]
Unfortunately I don't have a Windows machine available to build those wheels. Did you encounter problems when building from source? I've definitely built it successfully from source on Windows in the past.

**Comment by peterchenadded** [comment]
Thanks for the quick response.

Actually I haven't built it but can try, I have a windows machine.

**Comment by peterchenadded** [comment]
Cool i have built it, can i get your help to upload it to pypi? 

Also attached is the testing document, which you can review.

Please make sure to rename the .zip to .whl as github does not support uploading of whl.

[pyastar2d-1.0.2-cp38-cp38-win_amd64.zip](https://github.com/hjweide/pyastar2d/files/8546846/pyastar2d-1.0.2-cp38-cp38-win_amd64.zip)
[Pyastar2d windows install.docx](https://github.com/hjweide/pyastar2d/files/8546843/Pyastar2d.windows.install.docx)

**Comment by hjweide** [comment]
> Cool i have built it, can i get your help to upload it to pypi?

Done! Please check the wheel and let me know if anything is wrong. Thanks for your help and your patience.

I tried to make Travis build and publish the wheels automatically during the CI, but I ran into some version issues I couldn't figure out. Does this error I pasted in this PR look familiar to you?

https://github.com/hjweide/pyastar2d/pull/30

**Comment by peterchenadded** [comment]
@hjweide 

Looks good, was able to download without issues for windows 10, see below:

![image](https://user-images.githubusercontent.com/10074427/165007594-333cd48b-b4a4-4dfa-acf5-c9b67f5761b9.png)
