### ISSUE TITLE
Moving imageio from requirements.txt to requirements-dev.txt?

### ISSUE THREAD

**Issue by yudonglin** [hjweide/pyastar2d#38]
Since the "imageio" package is only used in [maze_solver.py](https://github.com/hjweide/pyastar2d/blob/master/examples/maze_solver.py) example, maybe it is a good idea to ask the user to install the "imageio" individually.
On the other hand, if a user is trying to use a Python version that is not supported by "imageio" (for instance, python 2 or 3.6), he/she may have trouble installing this package, and I did not see any reason this package cannot correctly run on most python versions.

**Comment by hjweide** [comment]
Good point. I’d be okay with moving imageio to the requirements-dev.txt and
updating the README to reflect that. Do you want to submit a PR for that?

But I hope not too many people are using these old Python versions anymore
:)

**Comment by yudonglin** [comment]
@hjweide Sure, I just made the pull request regarding this issue. Please review it, and thank you for giving me a chance to do so.

**Comment by hjweide** [comment]
Thanks for doing this so quickly! I’ll take a look tomorrow.
