### ISSUE TITLE
A case for no path found

### ISSUE THREAD

**Issue by rllyryan** [hjweide/pyastar2d#44]
Hi @hjweide,

Thank you for answering my questions in the previous issue!

I would like to ask if there is a checker for the case of "No Path Found", where it will return a value that denotes that the two points cannot be connected to each other.

I have tried the utility with a point outside an outlined box, and the other being located inside the box's whitespace. This is my result:
```
(149, 260)
None
Traceback (most recent call last):
  File "/home/rllyryan/Documents/GitHub/multi_agent_reinforcement_learning/development/1_project_preamble/prototype/Sandboxing/pyastar2d_test.py", line 46, in <module>
    maze[path[:, 0], path[:, 1]] = (0, 255, 0)
TypeError: 'NoneType' object is not subscriptable
```

May I ask what should I do to go about this?

Thank you!

**Comment by hjweide** [comment]
It returns None when there is no path. You are trying to plot plot None as
a path, hence the error.
